### ISSUE TITLE
Custom keybind resets everytime I restart Blender

### ISSUE THREAD

**Issue by pikachu1001000** [emptybraces/Blender-MyBestPieMenuEver#1]
If I set the keybind to something else, eg. Tab, and I restart Blender, the key bind will be reset back to the default 'W' key.

**Comment by emptybraces** [comment]
Hi,
Thank you for reporting! I'll check and fix it.

**Comment by emptybraces** [comment]
Now uploaded to blender extension. I'm check both v4.1 and v4.2, and see no problem.
Thank you for report and review^^

**Comment by pikachu1001000** [comment]
Hi. The update has removed the config area. 
<img width="760" alt="Screenshot 2024-07-24 160553" src="https://github.com/user-attachments/assets/ea983aa8-c1d3-4228-ac78-d112eb6e72b3">

**Comment by emptybraces** [comment]
hm, different from me, why.
Could you try reinstall again? Uninstall then install.
![image](https://github.com/user-attachments/assets/5b0e4935-29e2-4de5-8b97-adc22964c341)

**Comment by pikachu1001000** [comment]
Reinstalling did not fix the issue. So I tried booting Blender in factory mode and installing it then and I got this error.
![image](https://github.com/user-attachments/assets/936f71a4-2b0d-43b1-85e9-c22580c9f5cd)

**Comment by emptybraces** [comment]
Okay, can you see the console? I want know where lines error occured.
![image](https://github.com/user-attachments/assets/20cbd6f8-9b9b-4ca9-bced-edf3ea76f9f0)

**Comment by emptybraces** [comment]
is there nothing 3D View category?
![image](https://github.com/user-attachments/assets/bae88927-fce0-4d31-ba4b-51af32a6558c)

**Comment by emptybraces** [comment]
Okay maybe the problems you met has been fixed. I update to v1.3.8 to blender extensions.
The location where the error occurred is a bit of a bad spot, so please reinstall with the following procedure just to be sure.
- Uninstall addon.
- Close blender.
- Restart blender and reinstall addon.

**Comment by pikachu1001000** [comment]
Hi. The issue was not solved, partially. The config area was still not visible. However, with a bit of luck, I was able to add the input mapping manually to the 3D View (Global) category. I was able to select the correct action. I do hope that I'm the only one with this strange issue.
![image](https://github.com/user-attachments/assets/66b1dc7a-1265-4a61-8a93-7a1cdb5fbfb5)

**Comment by emptybraces** [comment]
If you have the time, it would be helpful if you could show me any errors that should be output to the console.
Maybe you did not follow the above steps to restart blender?
